# Generated by Django 5.2.14 on 2026-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_semester_enrollment_final_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
