# Generated by Django 5.2.14 on 2026-05-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_program_course_program_student_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=40)),
                ('drop_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.staff')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering'),
        ),
    ]
