# Generated by Django 5.2.14 on 2026-05-14 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_courseoffering_enrollment_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='registration_close',
            field=models.DateField(default=datetime.date(2026, 9, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='registration_open',
            field=models.DateField(default=datetime.date(2026, 5, 1)),
            preserve_default=False,
        ),
    ]
