# Generated by Django 5.2.14 on 2026-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_programcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
