# Generated by Django 5.2.14 on 2026-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_student_profile_number_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
    ]
