# Generated by Django 5.2.14 on 2026-06-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_enrollment_status_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('performed_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
