# Generated by Django 5.2.14 on 2026-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_activitylog_remove_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='ENROLLED', max_length=20),
        ),
    ]
